//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace KX12To13Converter.Pages.CMSModules.KX12To13Converter.UpgradeScripts
{


    public partial class ConvertForms
    {

        /// <summary>
        /// lblConfigMode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrResult;

        /// <summary>
        /// ddlConfigMode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtConfig;

        protected global::System.Web.UI.WebControls.TextBox txtDefaultSectionIdentifier;

        protected global::System.Web.UI.WebControls.TextBox txtDefaultSectionType;

        /// <summary>
        /// lbltemplateConfigJson control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnConvert;
    }
}